# Generated by Django 3.2.5 on 2021-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_title', models.CharField(max_length=50, verbose_name='Название Организации')),
                ('partner_logo', models.ImageField(upload_to='', verbose_name='Логотип партнера')),
                ('partner_link', models.URLField(blank=True, help_text='Необязательно', null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
