# Generated by Django 3.2.5 on 2021-07-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('deal_sort_desc', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('deal_full_desc', models.TextField(verbose_name='Описание')),
                ('deal_date', models.DateField(verbose_name='Дата организации мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='inst_link',
            field=models.URLField(default='https://www.instagram.com/livedream_stav/', verbose_name='Ссылка на инстаграм'),
        ),
    ]
